### ISSUE TITLE
RequestError [HttpError]: Resource not accessible by integration

### ISSUE THREAD

**Issue by boozook** [parkerbxyz/suggest-changes#15]
```
file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:7957
      const error = new import_request_error.RequestError(toErrorMessage(data), status, {
                    ^
```

Caused [here](https://github.com/boozook/playdate/actions/runs/8554683394/job/23440499611?pr=270#step:5:20).

<details><summary>Full crack log</summary>

```
file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:7957
      const error = new import_request_error.RequestError(toErrorMessage(data), status, {
                    ^

RequestError [HttpError]: Resource not accessible by integration
    at file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:7957:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:36507:3 {
  status: 403,
  response: {
    url: 'https://api.github.com/repos/boozook/playdate/pulls/270/reviews',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Thu, 04 Apr 2024 12:32:18 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'pull_requests=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': '5098:35D8:3C18501:611EFEB:660E9DD2',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4986',
      'x-ratelimit-reset': '1712236137',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '14',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/pulls/reviews#create-a-review-for-a-pull-request'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/boozook/playdate/pulls/270/reviews',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'suggest-changes octokit-core.js/4.2.4 Node.js/20.8.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"event":"REQUEST_CHANGES","body":"Rustfmt suggested the formatting changes.","comments":[{"path":"support/utils/src/compile.rs","start_line":7,"line":13,"start_side":"RIGHT","side":"RIGHT","body":"````suggestion\\n/// - fist positional - artifact path\\n/// - _this args_\\n/// - output path `-o`\\npub const GCC_ARGS_LIB: &[&str] = &[\\"-nostartfiles\\",\\n                                    \\"-mthumb\\",\\n                                    \\"-mcpu=cortex-m7\\",\\n                                    \\"-mfloat-abi=hard\\",\\n````"}]}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  }
}

Node.js v20.8.1
```

</details>

**Comment by echoix** [comment]
You might want to make sure that your use case works properly with pull requests from forks, I was suprised when I first tried out this action. It is a limitation of GitHub Actions.

**Comment by parkerbxyz** [comment]
Thanks for opening this issue, @boozook. I just opened the following pull request to add the permissions configuration to the example workflow in the README: https://github.com/parkerbxyz/suggest-changes/pull/18.

@echoix Just out of curiosity, did you get this action working with pull requests from forks? Perhaps another documentation update could help others that encounter this in the future.

**Comment by echoix** [comment]
No, it's kind of impossible as per the second column from this table: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

It's difficult to do it right so users (us) don't make something not safe enough. And forget about using pull_request_target, it's not safe to checkout the pull request fork, it defeats the whole purpose.

**Comment by echoix** [comment]
In the end I ended up using reviewdog in an unintended way with workflow_run event type (had to read the Go source code to know what variables to override), since this action didn't work the first time, it tried to add comments of lines outside of the changes context (lines that are outside of the changed lines, ie, lines that you couldn't add review comments even if you tried in the web interface). It either made the run fail or had a warning, I forgot. Reviewdog has more logic to handle these cases, but adds some kind of watermark in the comments.

**Comment by boozook** [comment]
Isn't it possible with defined `permissions` and using `pull_request_target` instead of just `pull_request`?

**Comment by parkerbxyz** [comment]
If you need [additional permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions) not offered by the default GITHUB_TOKEN, you can use a GitHub App token. I'm also a maintainer of [actions/create-github-app-token](https://github.com/actions/create-github-app-token), which makes it easy to use GitHub App tokens in GitHub Actions workflows.

**Comment by echoix** [comment]
> If you need [additional permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions) not offered by the default GITHUB_TOKEN, you can use a GitHub App token. I'm also a maintainer of [actions/create-github-app-token](https://github.com/actions/create-github-app-token), which makes it easy to use GitHub App tokens in GitHub Actions workflows.

I didn't know you could blend GitHub Apps with actions. Every time I stumble on something that leads to "needs to be a GitHub app", and read on what I need to do to make a GitHub App, they always loose me at the point where you require to have a server on the other end. I'm used to do CI; backend and infrastructure is always a bit too big and out of my league (at least for now), it isn't a simple CI workflow to assure everything still works as it should anymore.

**Comment by echoix** [comment]
> Isn't it possible with defined `permissions` and using `pull_request_target` instead of just `pull_request`?
> 
> - - - 
> UPD:
> > And forget about using pull_request_target, it's not safe to checkout the pull request fork, it defeats the whole purpose.
> 
> Oh, that's sad 😔 

The danger comes (in part) with executing untrusted code. It can be through compiling it, then running tests, where it is obvious. It _should_ be possible to stay safe even if checking out the pull request from a fork with write permissions, and to simply run static scans on it, but the line is so thin. The danger can be less obvious, as sometimes only doing a `npm install` is enough to be unsafe (see: pre and post scripts).

So it's a good thing that GitHub tries to prevent us from shooting ourselves in the foot, as it seems it already has been possible to do so in the past.

**Comment by parkerbxyz** [comment]
> > If you need [additional permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions) not offered by the default GITHUB_TOKEN, you can use a GitHub App token. I'm also a maintainer of [actions/create-github-app-token](https://github.com/actions/create-github-app-token), which makes it easy to use GitHub App tokens in GitHub Actions workflows.
> 
> I didn't know you could blend GitHub Apps with actions. Every time I stumble on something that leads to "needs to be a GitHub app", and read on what I need to do to make a GitHub App, they always loose me at the point where you require to have a server on the other end. I'm used to do CI; backend and infrastructure is always a bit too big and out of my league (at least for now), it isn't a simple CI workflow to assure everything still works as it should anymore.

No need to deploy anything or have a server in this case. Detailed instructions for how to accomplish this can be found here: https://docs.github.com/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow.
