### ISSUE TITLE
Error: Dynamic require of "os" is not supported

### ISSUE THREAD

**Issue by parkerbxyz** [parkerbxyz/suggest-changes#25]
> Could you plz tell me what I'm doing wrong [there](https://github.com/boozook/playdate/actions/runs/8618783304/job/23621961792?pr=277#step:5:16)?
> 
> ```text
> file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:12
>   throw Error('Dynamic require of "' + x + '" is not supported');
>         ^
> 
> Error: Dynamic require of "os" is not supported
>     at file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:12:9
>     at node_modules/@actions/core/lib/command.js (file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:108:27)
>     at __require2 (file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:18:50)
>     at node_modules/@actions/core/lib/core.js (file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:18302:21)
>     at __require2 (file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:18:50)
>     at file:///home/runner/work/_actions/parkerbxyz/suggest-changes/v1/dist/index.js:40139:27
>     at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
>     at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
>     at async loadESM (node:internal/process/esm_loader:34:7)
>     at async handleMainPromise (node:internal/modules/run_main:66:12)
> 
> Node.js v20.8.1
> ```

_Originally posted by @boozook in https://github.com/parkerbxyz/suggest-changes/discussions/24_

**Comment by parkerbxyz** [comment]
Looks like this might be a bug in the latest version. Could you try using a previous version of this action to see if you get the same error?

```yaml
- uses: parkerbxyz/suggest-changes@v1.0.2
```

**Comment by parkerbxyz** [comment]
This should be resolved now in the latest release: https://github.com/parkerbxyz/suggest-changes/releases/tag/v1.0.4

**Comment by boozook** [comment]
@parkerbxyz Yup, thanks, seems to `1.0.2` [works](https://github.com/boozook/playdate/actions/runs/8619928254/job/23625678242?pr=287#step:5:1) fine. 👍

**Comment by boozook** [comment]
> This should be resolved now in the latest release...

Agree, just tested `1.0.4` - works 👍, thanks!
